name: Release

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  release:
    environment: prod
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # It's important to fetch all history for Semantic Release to work

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the Node.js version compatible with your project

      - name: Install Dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
